fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "load_config",
            "save_config",
            "load_preferences",
            "save_preferences",
            "delete_session",
            "delete_group",
            "delete_rule",
            "create_group",
            "export_config",
            "import_config",
            "save_session_secret",
            "secret_store_status",
            "initialize_secrets",
            "unlock_secrets",
            "recover_secrets",
            "change_master_password",
            "lock_secrets",
            "approve_host_key",
            "connect_session",
            "disconnect_session",
            "start_rule",
            "stop_rule",
            "start_enabled_rules",
            "stop_session_rules",
            "poll_transports",
        ]),
    ))
    .expect("failed to build Tauri application permissions")
}
