<script setup lang="ts">
import { ref, watch } from 'vue'
const props = defineProps<{ open: boolean; mode: 'import' | 'export'; exportJson?: string }>()
const emit = defineEmits<{ close: []; confirm: [json: string, replaceAll: boolean] }>()
const json = ref('')
watch(() => props.exportJson, (value) => { json.value = value ?? '' }, { immediate: true })
</script>
<template><div v-if="open" class="backdrop" role="dialog" aria-modal="true"><section class="dialog"><h2>{{mode==='import'?'导入配置':'导出配置'}}</h2><p v-if="mode==='export'">导出文件只包含分组、会话非敏感字段和 Local 转发规则；不会包含密码、私钥口令、私钥内容或应用主密码。</p><p v-else>粘贴 Via 导出的 JSON。可合并现有配置，或覆盖全部配置。</p><textarea v-model="json" :readonly="mode==='export'" :placeholder="mode==='import' ? '粘贴 JSON 配置' : ''" aria-label="配置 JSON"/><footer><button @click="emit('close')">取消</button><button v-if="mode==='import'" :disabled="!json.trim()" @click="emit('confirm',json,false)">合并导入</button><button v-if="mode==='import'" class="danger" :disabled="!json.trim()" @click="emit('confirm',json,true)">覆盖全部</button><button v-else class="primary" @click="emit('confirm',json,false)">复制 JSON</button></footer></section></div></template>
<style scoped>.backdrop{position:fixed;inset:0;display:grid;place-items:center;background:#0008;z-index:10}.dialog{width:min(460px,calc(100vw - 32px));border:1px solid var(--line);border-radius:10px;background:var(--surface);padding:20px;box-shadow:0 22px 80px #0008}.dialog h2{margin:0;font-size:16px}.dialog p{color:var(--muted);font-size:13px;line-height:1.6}.dialog textarea{width:100%;min-height:160px;border:1px solid var(--line);border-radius:6px;background:var(--canvas);padding:8px;color:var(--text);font:12px ui-monospace,monospace;resize:vertical}.dialog footer{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.dialog button{border:1px solid var(--line);border-radius:6px;background:var(--surface-raised);padding:7px 10px;color:var(--text);cursor:pointer}.dialog .primary{background:#1f6feb}.dialog .danger{border-color:#f8514970;color:#ff7b72}</style>
